#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ $ENABLE_MYMPD == "true" ] && [ $USER_ID -ne 0 ]; then
	echo "false"
else
	echo "true"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
