#! /usr/bin/with-contenv bash

# 启动calibre-server
if [ -n "$USER" ] && [ -n "$PASSWORD" ] ;  then
  exec s6-setuidgid calibre  calibre-server /library --userdb /config/calibre-server/calibre/server-users.sqlite --enable-auth
else
  exec s6-setuidgid calibre  calibre-server /library
fi
