#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

if [ "$ENABLE_MPD_TEST" == "true" ]; then
   exec /usr/local/bin/mpd-test $HOME/mpd/mpd.conf --no-daemon
else
   exec /usr/local/bin/mpd $HOME/mpd/mpd.conf --no-daemon
fi
# vim:ft=sh:ts=4:sw=4:et:sts=4
