#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

[ -e /var/run/dbus/system_bus_socket ] && [ `ps | grep "dbus-daemon --config-file=/usr/share/dbus-1/system.conf" |grep -v grep |wc -l` -eq 1 ]

# vim:ft=sh:ts=4:sw=4:et:sts=4
