#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

exec dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address --nopidfile --nofork

# vim:ft=sh:ts=4:sw=4:et:sts=4
