#! /usr/bin/with-contenv bash

# 启动inotify
while inotifywait -e close -e modify $HOME/.config/joplin/log-clipper.txt; do
    inotifywait -m $HOME/.config/joplin/log-clipper.txt -t 60
    su -p koreader -s /bin/bash -c "joplin sync"
done
