#! /bin/bash

# 启动aria2
if [ ! -n "$RPC_SECRET" ] ;  then 
aria2c --conf-path=$CONFIG/aria2.conf --enable-rpc --rpc-listen-all   -D
else 
aria2c --conf-path=$CONFIG/aria2.conf --enable-rpc --rpc-listen-all --rpc-secret="$RPC_SECRET" -D
fi

#启动 caddy
caddy --conf /etc/caddy/caddy.conf &


#启动trackers更新任务
crond -L /dev/null
