name: postgres

on:
  push:
    paths:
    - '.github/workflows/postgres.yml'
  workflow_dispatch:

env:
  ALPINE_VER: 3.17

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: download postgres src
        run: |
          sudo apt-get update
          sudo apt-get install  git
          git clone https://github.com/docker-library/postgres.git
          sed -i '/ENV PG_MAJOR 14/i\ENV LLVM_CONFIG=/usr/lib/llvm14/bin/llvm-config' postgres/14/alpine/Dockerfile
          sed -i 's/llvm-dev/llvm14-dev/g' postgres/14/alpine/Dockerfile
          sed -i 's/clang/clang14/g' postgres/14/alpine/Dockerfile
          sed -i 's/coreutils/coreutils patch/g' postgres/14/alpine/Dockerfile
          sed -i 's/^ENV.*PG_VERSION.*/ENV PG_VERSION 14.1/g' postgres/14/alpine/Dockerfile
          sed -i 's/^ENV.*PG_SHA256.*/ENV PG_SHA256 4d3c101ea7ae38982f06bdc73758b53727fb6402ecd9382006fa5ecc7c2ca41f/g' postgres/14/alpine/Dockerfile
          sed -i '/cd \/usr\/src\/postgresql; \\/a\\ \ \ \ patch -p1 < llvm14-support.patch; \\ '  postgres/14/alpine/Dockerfile
          sed -i '/cd \/usr\/src\/postgresql; \\/a\\ \ \ \ wget https://raw.githubusercontent.com/gshang2017/docker/master/tt-rss-plugins/postgresql/patches/llvm14-support.patch; \\ '  postgres/14/alpine/Dockerfile

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./postgres/14/alpine
          file: ./postgres/14/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/gshang2017/postgres:latest
            ghcr.io/gshang2017/postgres:14.1-alpine-${{ env.ALPINE_VER }}
