name: postgres

on:
  push:
    paths:
    - '.github/workflows/postgres.yml'
  workflow_dispatch:

env:
  ALPINE_VER: 3.23

jobs:
  job1:
    name: buildx tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download postgres src
        run: |
          sudo apt-get update
          sudo apt-get install  git
          git clone https://github.com/docker-library/postgres.git
          sed -i 's/^ENV.*PG_VERSION.*/ENV PG_VERSION 17.9/g' postgres/17/alpine3.23/Dockerfile
          sed -i 's/^ENV.*PG_SHA256.*/ENV PG_SHA256 3b9a62538a8da151e807a3ddb1198e8605f2032544d78f403ae883d27ecf1ee4/g' postgres/17/alpine3.23/Dockerfile

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./postgres/17/alpine3.23
          file: ./postgres/17/alpine3.23/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/gshang2017/postgres:latest
            ghcr.io/gshang2017/postgres:17.9-alpine-${{ env.ALPINE_VER }}
